networks:
  crete-network:
    driver: bridge
    attachable: true

services:
  orderer.crete.com:
    container_name: orderer.crete.com
    hostname: orderer.crete.com
    image: hyperledger/fabric-orderer:2.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - CORE_PEER_TLS_ENABLED=true
    working_dir: /var/hyperledger/orderer
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/crete.com/orderers/orderer.crete.com:/var/hyperledger/orderer
      - ./channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesisblock
    ports:
      - "7050:7050"
      - "8443:8443"
    networks:
      - crete-network

  # Peer for Heraklion
  peer0.heraklion.crete.com:
    container_name: peer0.heraklion.crete.com
    hostname: peer0.heraklion.crete.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.heraklion.crete.com
      - CORE_PEER_ADDRESS=peer0.heraklion.crete.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.heraklion.crete.com:7052
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/msp/tlscacerts/tlsca.heraklion.crete.com-cert.pem
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.heraklion.crete.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.heraklion.crete.com:7051
      - CORE_PEER_LOCALMSPID=HeraklionMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ./crypto-config/peerOrganizations/heraklion.crete.com/peers/peer0.heraklion.crete.com/msp:/var/hyperledger/msp
      - ./channel-artifacts:/var/hyperledger/channel-artifacts
      - ./crypto-config/peerOrganizations/heraklion.crete.com/peers/peer0.heraklion.crete.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - "7051:7051"
      - "7052:7052"
    networks:
      - crete-network

  # Peer for Chania
  peer0.chania.crete.com:
    container_name: peer0.chania.crete.com
    hostname: peer0.chania.crete.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.chania.crete.com
      - CORE_PEER_ADDRESS=peer0.chania.crete.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_CHAINCODEADDRESS=peer0.chania.crete.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.chania.crete.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.chania.crete.com:8051
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/msp/tlscacerts/tlsca.chania.crete.com-cert.pem
      - CORE_PEER_LOCALMSPID=ChaniaMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ./crypto-config/peerOrganizations/chania.crete.com/peers/peer0.chania.crete.com/msp:/var/hyperledger/msp
      - ./channel-artifacts:/var/hyperledger/channel-artifacts
      - ./crypto-config/peerOrganizations/chania.crete.com/peers/peer0.chania.crete.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - "8051:8051"
      - "8052:8052"
    networks:
      - crete-network

  # Peer for Rethymno
  peer0.rethymno.crete.com:
    container_name: peer0.rethymno.crete.com
    hostname: peer0.rethymno.crete.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.rethymno.crete.com
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ADDRESS=peer0.rethymno.crete.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rethymno.crete.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rethymno.crete.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rethymno.crete.com:9051
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/msp/tlscacerts/tlsca.rethymno.crete.com-cert.pem
      - CORE_PEER_LOCALMSPID=RethymnoMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ./crypto-config/peerOrganizations/rethymno.crete.com/peers/peer0.rethymno.crete.com/msp:/var/hyperledger/msp
      - ./channel-artifacts:/var/hyperledger/channel-artifacts
      - ./crypto-config/peerOrganizations/rethymno.crete.com/peers/peer0.rethymno.crete.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - "9051:9051"
      - "9052:9052"
    networks:
      - crete-network

  # Peer for Lasithi
  peer0.lasithi.crete.com:
    container_name: peer0.lasithi.crete.com
    hostname: peer0.lasithi.crete.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_PEER_ID=peer0.lasithi.crete.com
      - CORE_PEER_ADDRESS=peer0.lasithi.crete.com:10051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lasithi.crete.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lasithi.crete.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lasithi.crete.com:10051
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/msp/tlscacerts/tlsca.lasithi.crete.com-cert.pem
      - CORE_PEER_LOCALMSPID=LasithiMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - ./crypto-config/peerOrganizations/lasithi.crete.com/peers/peer0.lasithi.crete.com/msp:/var/hyperledger/msp
      - ./channel-artifacts:/var/hyperledger/channel-artifacts
      - ./crypto-config/peerOrganizations/lasithi.crete.com/peers/peer0.lasithi.crete.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - "10051:10051"
      - "10052:10052"
    networks:
      - crete-network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4
    tty: true
    stdin_open: true
    environment:
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.heraklion.crete.com:7051
      - CORE_PEER_LOCALMSPID=HeraklionMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/heraklion.crete.com/peers/peer0.heraklion.crete.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/heraklion.crete.com/peers/peer0.heraklion.crete.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/heraklion.crete.com/tlsca/tlsca.heraklion.crete.com-cert.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/heraklion.crete.com/users/Admin@heraklion.crete.com/msp
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_BCCSP_DEFAULT=SW
      - CORE_BCCSP_SW_SECURITY=256
      - CORE_BCCSP_SW_HASH=SHA2
      - CORE_BCCSP_SW_FILEKEYSTORE_KEYSTORE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/heraklion.crete.com/users/Admin@heraklion.crete.com/msp/keystore
    volumes:
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./crypto-config/peerOrganizations/heraklion.crete.com/peers/peer0.heraklion.crete.com/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
    command: /bin/bash
    networks:
      - crete-network
